[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "assets"]

[serve]
port = 8080

[[proxy]]
backend = "http://localhost:8081"

[[hooks]]
stage = "pre_build"
command = "scripts/select_index.sh"
