[workspace]
members = ["frontend", "runner", "server", "shared"]
resolver = "2"

[workspace.package]
version = "0.3.4"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
iggy-bench-report = { git = "https://github.com/apache/iggy.git", branch = "bench-random" }
