[workspace]
members = ["frontend", "runner", "server"]
resolver = "2"

[workspace.package]
version = "0.2.3"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
iggy-benchmark-report = { git = "https://github.com/iggy-rs/iggy.git", version = "0.1.2" }
