[workspace]
members = ["frontend", "runner", "server", "shared"]
resolver = "2"

[workspace.package]
version = "0.3.2"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
iggy-bench-report = { git = "https://github.com/iggy-rs/iggy.git", branch = "bench-no-title-chart" }
