[package]
name = "iggy-dashboard-server"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-governor = "0.5"
actix-web = "4.9.0"
clap = { version = "4.4", features = ["derive"] }
dashmap = "5.5.3"
notify = "6.1.1"
rayon = "1.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shared = { path = "../shared" }
thiserror = "2.0.11"
time = { version = "0.3", features = ["formatting"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
