[package]
name = "shared"
license = "Apache-2.0"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
iggy-benchmark-report = { git = "https://github.com/iggy-rs/iggy.git" }
uuid = { version = "1.12.1", features = ["serde"] }
