{
 "title": "Consumers performance on read",
 "time": { "from": "2024-12-01T20:14:34.099Z", "to": "2024-12-09T15:08:27.919Z" },
 "panels": [
  {
   "title": "Throughput - 8 consumers, 1000 batches, 1000 messages per batch, 1000 bytes per message",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  git_ref, total_throughput_megabytes_per_second\nFROM\n  performance_metrics\nWHERE\n  benchmark_name = 'poll messages' AND\n  message_size = '1000' AND\n  messages_per_batch = '1000' AND\n  message_batches = '1000' AND\n  consumers = '8' AND\n  producers = '0'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Messages/s - 8 consumers, 1000 batches, 1000 messages per batch, 1000 bytes per message",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  git_ref, total_throughput_messages_per_second\nFROM\n  performance_metrics\nWHERE\n  benchmark_name = 'poll messages' AND\n  message_size = '1000' AND\n  messages_per_batch = '1000' AND\n  message_batches = '1000' AND\n  consumers = '8' AND\n  producers = '0'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency - 8 consumers, 1000 batches, 1000 messages per batch, 1000 bytes per message",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT\n  git_ref, average_avg_latency_ms, average_p99_latency_ms\nFROM\n  performance_metrics\nWHERE\n  benchmark_name = 'poll messages' AND\n  message_size = '1000' AND\n  messages_per_batch = '1000' AND\n  message_batches = '1000' AND\n  consumers = '8' AND\n  producers = '0'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}