name: build-and-test
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      - name: Install wasm-target
        run: rustup target add wasm32-unknown-unknown

      - name: Build Frontend
        run: |
          cd frontend
          trunk build --release

      - name: Build Server
        run: cargo build --release --package iggy-bench-dashboard-server

      - name: Build Runner
        run: cargo build --release --package iggy-bench-runner

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --all-features --workspace
