name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # Run sanity checks first
  sanity:
    uses: ./.github/workflows/sanity.yml

  # Run build and test after sanity checks
  build-and-test:
    needs: sanity
    uses: ./.github/workflows/build-and-test.yml

  # Trigger Docker workflow if needed
  trigger-docker:
    needs: [sanity, build-and-test]
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
